---
title: "Country by country: how coronavirus case trajectories compare"
output: html_document
---

The code below is an attempt at recreating John Burn-Murdoch's [coronavirus graphs published in the Financial Times](https://www.ft.com/content/a26fbf7e-48f8-11ea-aeb3-955839e06441) using ggplot2 and [data from the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19).

Load packages and configure:
  
```{r message = FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(gghighlight)
library(wesanderson)
library(glue)

baseline <- 100
countries <- c("Belgium", "Italy", "Japan", "France", "United Kingdom")
slope <- 33
dot_size <- 1.5
line_width <- 0.8
```

Load and transform data:

```{r message = FALSE}
df <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv")
ndays <- ncol(df) - 4
names(df) <- c("state", "country", "lat", "lon", seq(1:ndays))

df_long <- df %>%
  gather(day, cases, 5:ncol(df)) %>%
  mutate(day = as.numeric(day)) %>%
  select(-lat, -lon) %>%
  group_by(country, day) %>%
  summarize(cases = sum(cases))

series <- df_long %>%
  filter(cases >= baseline) %>%
  group_by(country) %>%
  mutate(day = min_rank(day) - 1) %>%
  arrange(country, day)

endpoints <- series %>%
  group_by(country) %>%
  summarize(day = last(day), cases = last(cases))
```

Plot:

```{r message = FALSE, warning = FALSE, fig.width = 12, fig.fullwidth = TRUE}
ggplot() +
  geom_abline(intercept = 2, slope = log10(1 + slope / 100), linetype = "dashed", color = "#aaaaaa", size = 0.6) +
  geom_line(data = series, aes(x = day, y = cases, color = country), size = line_width) +
  geom_point(data = series, aes(x = day, y = cases, color = country), size = dot_size) +
  geom_text(data = endpoints, aes(x = day, y = cases, label = country, color = country), size = 4, hjust = 0, nudge_x = 0.5) +
  geom_point(data = endpoints, aes(x = day, y = cases), size = dot_size, shape = 21) +
  gghighlight(country %in% countries, use_direct_label = FALSE, unhighlighted_params = list(colour = alpha("#dadada", 1))) +
  geom_text(data = data.frame(x = 20, y = 100 * (1 + slope / 100)^20, label = glue("{slope}% DAILY INCREASE")), aes(x = x, y = y, label = label), size = 3, angle = atan(log10(1 + slope / 100) * 10) * 180 / pi, vjust = 0, nudge_y = 0.03) +
  scale_x_continuous(n.breaks = 8) +
  scale_y_log10(n.breaks = 8, labels = function(x) format(x, big.mark = ",", scientific = FALSE)) +
  scale_color_manual(values = wes_palette("Darjeeling1", length(countries))) +
  coord_fixed(10) +
  theme_light() +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.line.x = element_line(size = 0.2),
    plot.background = element_rect(fill = "#fff9f5"),
    panel.background = element_rect(fill = "#fff9f5"),
    plot.title.position = "plot"
  ) +
  xlab("Number of days since 100th case") +
  ylab("") +
  labs(title = "Country by country: how coronavirus case trajectories compare", subtitle = "Cumulative number of cases, by number of days since 100th case")
```
